import 'package:flut_mart/utils/models/product.model.dart';

final List<Product> allProducts = [
  Product(
    id: 1,
    name: 'Macbook Pro',
    image: 'assets/images/macbook.png',
    price: 1200,
    discount: 10,
    description: 'Apple Macbook Pro 13-inch',
    categoryId: 1,
    rating: 4.5,
    noOfReviews: 23,
  ),
  Product(
    id: 1,
    name: 'Samsung Galaxy S21',
    image: 'assets/images/macbook.png',
    price: 950,
    discount: 30,
    description: 'Samsung Galaxy S21 Ultra 5G 128GB 12GB RAM',
    categoryId: 1,
    rating: 4.8,
    noOfReviews: 123,
  ),
  Product(
    id: 2,
    name: 'T-shirt',
    image: 'assets/images/tshirt.png',
    price: 20,
    discount: 5,
    description: 'Men\'s Casual Slim Fit',
    categoryId: 2,
    rating: 4.0,
    noOfReviews: 10,
  ),
  Product(
    id: 3,
    name: 'Shoes',
    image: 'assets/images/shoe.png',
    price: 50,
    discount: 15,
    description: 'Men\'s Running Shoe',
    categoryId: 3,
    rating: 4.2,
    noOfReviews: 15,
  ),
  Product(
    id: 4,
    name: 'Chair',
    image: 'assets/images/shoe.png',
    price: 100,
    discount: 20,
    description: 'Wooden Dining Chair',
    categoryId: 4,
    rating: 4.8,
    noOfReviews: 30,
  ),
  Product(
    id: 5,
    name: 'Book',
    image: 'assets/images/macbook.png',
    price: 10,
    discount: 0,
    description: 'The Great Gatsby',
    categoryId: 5,
    rating: 4.9,
    noOfReviews: 50,
  ),
  Product(
    id: 6,
    name: 'Lipstick',
    image: 'assets/images/shoe.png',
    price: 5,
    discount: 0,
    description: 'Red Lipstick',
    categoryId: 6,
    rating: 4.7,
    noOfReviews: 40,
  ),
  Product(
    id: 7,
    name: 'Dumbbell',
    image: 'assets/images/macbook.png',
    price: 30,
    discount: 0,
    description: '10kg Dumbbell',
    categoryId: 7,
    rating: 4.6,
    noOfReviews: 35,
  ),
  Product(
    id: 8,
    name: 'Toy',
    image: 'assets/images/shoe.png',
    price: 15,
    discount: 5,
    description: 'Kids Toy',
    categoryId: 8,
    rating: 4.3,
    noOfReviews: 20,
  ),
  Product(
    id: 9,
    name: 'Pen',
    image: 'assets/images/tshirt.png',
    price: 2,
    discount: 0,
    description: 'Blue Ballpoint Pen',
    categoryId: 10,
    rating: 4.1,
    noOfReviews: 18,
  ),
];
