import 'package:flut_mart/utils/models/product.model.dart';

final List<Product> allProducts = [
  Product(
    id: 1,
    name: 'Macbook Pro',
    image: 'assets/images/macbook.png',
    price: 999,
    discount: 10,
    description: 'Apple Macbook Pro 13-inch',
    categoryId: 1,
    rating: 4.5,
    noOfReviews: 23,
  ),
  Product(
    id: 10,
    name: 'Samsung Galaxy S21',
    image: 'assets/images/macbook.png',
    price: 950,
    discount: 30,
    description: 'Samsung Galaxy S21',
    categoryId: 1,
    rating: 4.8,
    noOfReviews: 123,
  ),
  Product(
    id: 11,
    name: 'Realme Narzo 20 Pro',
    image: "assets/images/macbook.png",
    price: 650,
    discount: 12,
    description: "New Random Phone in the market.",
    categoryId: 1,
    rating: 4.5,
    noOfReviews: 23,
  ),
  Product(
    id: 12,
    name: 'Samsung Galaxy S22',
    image: "assets/images/macbook.png",
    price: 950,
    discount: 30,
    description: "Samsung Galaxy S22",
    categoryId: 1,
    rating: 4.8,
    noOfReviews: 123,
  ),
  Product(
    id: 13,
    name: 'Nokia 256',
    image: "assets/images/macbook.png",
    price: 56,
    discount: 2,
    description: "New Random Phone in the market.",
    categoryId: 1,
    rating: 4.5,
    noOfReviews: 23,
  ),
  Product(
    id: 14,
    name: 'Samsung A20',
    image: "assets/images/macbook.png",
    price: 950,
    discount: 30,
    description: "12GB RAM",
    categoryId: 1,
    rating: 4.8,
    noOfReviews: 123,
  ),
  Product(
    id: 15,
    name: 'iPhone 14',
    image: "assets/images/macbook.png",
    price: 236,
    discount: 2,
    description: "New Random Phone in the market.",
    categoryId: 1,
    rating: 4.5,
    noOfReviews: 23,
  ),
  Product(
    id: 16,
    name: 'Realme 6 Pro',
    image: "assets/images/macbook.png",
    price: 950,
    discount: 30,
    description: "128GB",
    categoryId: 1,
    rating: 4.8,
    noOfReviews: 123,
  ),
  Product(
    id: 17,
    name: 'OnePlus 9T',
    image: "assets/images/macbook.png",
    price: 405,
    discount: 2,
    description: "New Random Phone in the market.",
    categoryId: 1,
    rating: 4.5,
    noOfReviews: 23,
  ),
  Product(
    id: 18,
    name: 'Huawei P30',
    image: "assets/images/macbook.png",
    price: 950,
    discount: 30,
    description: "Samsung Galaxy S21 Ultra",
    categoryId: 1,
    rating: 4.8,
    noOfReviews: 123,
  ),
  Product(
    id: 19,
    name: 'Samsung Fold 3',
    image: "assets/images/macbook.png",
    price: 698,
    discount: 2,
    description: "New Random Phone in the market.",
    categoryId: 1,
    rating: 4.5,
    noOfReviews: 23,
  ),
  Product(
    id: 20,
    name: 'Oppo Reno 6',
    image: "assets/images/macbook.png",
    price: 950,
    discount: 30,
    description: "Samsung Galaxy S21 Ultra 5G",
    categoryId: 1,
    rating: 4.8,
    noOfReviews: 123,
  ),
  Product(
    id: 21,
    name: 'Blackberry Key 3',
    image: "assets/images/macbook.png",
    price: 102,
    discount: 2,
    description: "New Random Phone in the market.",
    categoryId: 1,
    rating: 4.5,
    noOfReviews: 23,
  ),
  Product(
    id: 22,
    name: 'MI 11 Ultra',
    image: "assets/images/macbook.png",
    price: 950,
    discount: 30,
    description: "Samsung Galaxy S21 Ultra 5G 128GB 12GB RAM",
    categoryId: 1,
    rating: 4.8,
    noOfReviews: 123,
  ),
  Product(
    id: 23,
    name: 'Google Pixel 6',
    image: "assets/images/macbook.png",
    price: 968,
    discount: 2,
    description: "New Random Phone in the market.",
    categoryId: 1,
    rating: 4.5,
    noOfReviews: 23,
  ),
  Product(
    id: 24,
    name: 'Google Pixel 6 Pro',
    image: "assets/images/macbook.png",
    price: 950,
    discount: 30,
    description: "Samsung Galaxy S21 Ultra",
    categoryId: 1,
    rating: 4.8,
    noOfReviews: 123,
  ),
  Product(
    id: 25,
    name: 'IPhone 12 Pro Max',
    image: "assets/images/macbook.png",
    price: 758,
    discount: 2,
    description: "New Random Phone in the market.",
    categoryId: 1,
    rating: 4.5,
    noOfReviews: 23,
  ),
  Product(
    id: 26,
    name: 'MI 10T',
    image: "assets/images/macbook.png",
    price: 950,
    discount: 30,
    description: "Samsung Galaxy S21 Ultra 5G 128GB 12GB RAM",
    categoryId: 1,
    rating: 4.8,
    noOfReviews: 123,
  ),
  Product(
    id: 27,
    name: 'OnePlus 12T',
    image: "assets/images/macbook.png",
    price: 399,
    discount: 2,
    description: "New Random Phone in the market.",
    categoryId: 1,
    rating: 4.5,
    noOfReviews: 23,
  ),
  Product(
    id: 28,
    name: 'Oppo 12',
    image: "assets/images/macbook.png",
    price: 950,
    discount: 30,
    description: "Samsung Galaxy S21",
    categoryId: 1,
    rating: 4.8,
    noOfReviews: 123,
  ),
  Product(
    id: 29,
    name: 'Windows Phone',
    image: "assets/images/macbook.png",
    price: 789,
    discount: 2,
    description: "New Random Phone in the market.",
    categoryId: 1,
    rating: 4.5,
    noOfReviews: 23,
  ),
  Product(
    id: 30,
    name: 'Microsoft Surface',
    image: "assets/images/macbook.png",
    price: 950,
    discount: 30,
    description: "Samsung Galaxy S21 Ultra",
    categoryId: 1,
    rating: 4.8,
    noOfReviews: 123,
  ),
  Product(
    id: 31,
    name: 'IPhone 10 Mini',
    image: "assets/images/macbook.png",
    price: 145,
    discount: 2,
    description: "New Random Phone in the market.",
    categoryId: 1,
    rating: 4.5,
    noOfReviews: 23,
  ),
  Product(
    id: 32,
    name: 'Samsung B56',
    image: "assets/images/macbook.png",
    price: 950,
    discount: 30,
    description: "5G 128GB 12GB RAM",
    categoryId: 1,
    rating: 4.8,
    noOfReviews: 123,
  ),
  Product(
    id: 33,
    name: 'IPhone 5',
    image: "assets/images/macbook.png",
    price: 697,
    discount: 2,
    description: "New Random Phone in the market.",
    categoryId: 1,
    rating: 4.5,
    noOfReviews: 23,
  ),
  Product(
    id: 2,
    name: 'T-shirt',
    image: 'assets/images/tshirt.png',
    price: 20,
    discount: 5,
    description: 'Men\'s Casual Slim Fit',
    categoryId: 2,
    rating: 4.0,
    noOfReviews: 10,
  ),
  Product(
    id: 3,
    name: 'Shoes',
    image: 'assets/images/shoe.png',
    price: 50,
    discount: 15,
    description: 'Men\'s Running Shoe',
    categoryId: 3,
    rating: 4.2,
    noOfReviews: 15,
  ),
  Product(
    id: 4,
    name: 'Chair',
    image: 'assets/images/shoe.png',
    price: 100,
    discount: 20,
    description: 'Wooden Dining Chair',
    categoryId: 4,
    rating: 4.8,
    noOfReviews: 30,
  ),
  Product(
    id: 5,
    name: 'Book',
    image: 'assets/images/macbook.png',
    price: 10,
    discount: 0,
    description: 'The Great Gatsby',
    categoryId: 5,
    rating: 4.9,
    noOfReviews: 50,
  ),
  Product(
    id: 6,
    name: 'Lipstick',
    image: 'assets/images/shoe.png',
    price: 5,
    discount: 0,
    description: 'Red Lipstick',
    categoryId: 6,
    rating: 4.7,
    noOfReviews: 40,
  ),
  Product(
    id: 7,
    name: 'Dumbbell',
    image: 'assets/images/macbook.png',
    price: 30,
    discount: 0,
    description: '10kg Dumbbell',
    categoryId: 7,
    rating: 4.6,
    noOfReviews: 35,
  ),
  Product(
    id: 8,
    name: 'Toy',
    image: 'assets/images/shoe.png',
    price: 15,
    discount: 5,
    description: 'Kids Toy',
    categoryId: 8,
    rating: 4.3,
    noOfReviews: 20,
  ),
  Product(
    id: 9,
    name: 'Pen',
    image: 'assets/images/tshirt.png',
    price: 2,
    discount: 0,
    description: 'Blue Ballpoint Pen',
    categoryId: 9,
    rating: 4.1,
    noOfReviews: 18,
  ),
];
