name: flut_mart
description: "E-commerce App with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.2.2
  jwt_decoder: ^2.0.1
  lottie: ^3.1.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/

  fonts:
    - family: SUSE
      fonts:
        - asset: assets/fonts/SUSE-Regular.ttf
        - asset: assets/fonts/SUSE-Bold.ttf
          weight: 700